[[files]]
name = "{{.PackageName}}.go"
template = '''package {{.PackageName}}'''
[[files]]
name = "{{.PackageName}}_test.go"
template = '''package {{.PackageName}}

import "testing"

func Test(t *testing.T) {

}
'''
[[files]]
name = "README.md"
template = '''#{{.HumanizedPackageName}}
Some package doc.
'''