[[files]]
name = "README.md"
template = '''#Web api sample in Go

To run:
```shell
$ go build -o webapi; ./webapi
```

Open on localhost:3000.
'''

[[files]]
name = "main.go"
template = '''package main

import (
	"fmt"
	"log"
	"net/http"
)

func homeHandler(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World")
}

func main() {
	mux := http.NewServeMux()
	mux.HandleFunc("/", homeHandler)

	log.Println("listening on port 3000")
	log.Fatal(http.ListenAndServe(":3000", mux))
}

'''